feat(infra): route data plane traffic to gloo (#2504)
test plan:
#### unit tests
- [x] Gloo struct generation
#### e2e tests with new workspace url and deployment endpoint
- [x] Shared LB deployment external endpoint existence
  - testHostBasedIngressWithSharedLBInfra
- [x] Only dns propagation wait during workspace creation
  - testHostBasedIngressWithSharedLBInfra
- [x] CORS
- Dataplane: header based routing (with ingress_test.go
testHostBasedIngressWithSharedLBInfra)
  - [x] basic routing
  - [x] take precedence over control plane if header present
  - [x] multiple tokens and authentication
  - [x] wrong token/missing token
- Dataplane: host based routing (with ingress_test.go
testHeaderBasedIngress)
  - [x] basic routing
  - [x] multiple tokens (in headers)
  - [x] wrong token/missing token     
- Controlplane: (with ingress_test.go TestControlPlaneIngress)
  - [x] basic routing
  - [x] api token header
  - [x] query token (with TestReplicaShellQueryString)
  - [x] wrong token/missing token return 401
  - [x] 404

diff --git a/.github/workflows/run-e2e-tests.yaml b/.github/workflows/run-e2e-tests.yaml
--- a/.github/workflows/run-e2e-tests.yaml
+++ b/.github/workflows/run-e2e-tests.yaml
@@ -15,25 +15,30 @@ on:
         required: false
         type: string
         default: testws$(git rev-parse --short HEAD)
+      workspace_name_01:
+        required: false
+        type: string
+        default: testws01$(git rev-parse --short HEAD)
       api_token:
         required: false
         type: string
         default: token-testws$(git rev-parse --short HEAD)
+      api_token_01:
+        required: false
+        type: string
+        default: token-testws01$(git rev-parse --short HEAD)
 
 jobs:
-  e2e-tests:
+  find-cluster:
     runs-on: self-hosted
+    outputs:
+      cluster: ${{ steps.find_ci_cluster.outputs.cluster }}
     steps:
       - uses: actions/checkout@v3
       - name: Set up Go
         uses: actions/setup-go@v3
         with:
           go-version: 1.19.x
-      - name: Install Python 3.10
-        uses: actions/setup-python@v4
-        with:
-          python-version: "3.10"
-          cache: "pip" # caching pip dependencies
       - name: Build mothership cli
         run: |
           (cd mothership && go build -v ./cmd/mothership && mv mothership ../mothershipctl)
@@ -48,6 +53,23 @@ jobs:
             exit 1
           fi
           echo "cluster=$latest_ready_cluster" >> $GITHUB_OUTPUT
+  run-tests:
+    runs-on: self-hosted
+    needs: [find-cluster]
+    steps:
+      - uses: actions/checkout@v3
+      - name: Set up Go
+        uses: actions/setup-go@v3
+        with:
+          go-version: 1.19.x
+      - name: Install Python 3.10
+        uses: actions/setup-python@v4
+        with:
+          python-version: "3.10"
+          cache: "pip" # caching pip dependencies
+      - name: Build mothership cli
+        run: |
+          (cd mothership && go build -v ./cmd/mothership && mv mothership ../mothershipctl)
       - name: Create ci workspace and install sdk
         run: |
           # create ci workspace
@@ -55,7 +77,7 @@ jobs:
             --mothership-url https://mothership.cloud.lepton.ai/api/v1 \
             --token "${{ secrets.MOTHERSHIP_TOKEN }}" \
             --api-token "${{ inputs.api_token }}" \
-            --cluster-name "${{ steps.find_ci_cluster.outputs.cluster }}" \
+            --cluster-name "${{ needs.find-cluster.outputs.cluster }}" \
             --workspace-name "${{ inputs.workspace_name }}" \
             --git-ref "${{ inputs.git_ref }}" \
             --image-tag "${{ inputs.image_tag }}" \
@@ -90,5 +112,68 @@ jobs:
             --mothership-url https://mothership.cloud.lepton.ai/api/v1 \
             --token "${{ secrets.MOTHERSHIP_TOKEN }}" \
             --workspace-name "${{ inputs.workspace_name }}" \
+            --timeout 10 \
+            --expected-state "deleted"
+  run-tests-shared-alb:
+    runs-on: self-hosted
+    needs: [find-cluster]
+    steps:
+      - uses: actions/checkout@v3
+      - name: Set up Go
+        uses: actions/setup-go@v3
+        with:
+          go-version: 1.19.x
+      - name: Install Python 3.10
+        uses: actions/setup-python@v4
+        with:
+          python-version: "3.10"
+          cache: "pip" # caching pip dependencies
+      - name: Build mothership cli
+        run: |
+          (cd mothership && go build -v ./cmd/mothership && mv mothership ../mothershipctl)
+      - name: Create ci workspace and install sdk
+        run: |
+          # create ci workspace
+          ./mothershipctl workspace create \
+            --mothership-url https://mothership.cloud.lepton.ai/api/v1 \
+            --token "${{ secrets.MOTHERSHIP_TOKEN }}" \
+            --api-token "${{ inputs.api_token_01 }}" \
+            --cluster-name "${{ needs.find-cluster.outputs.cluster }}" \
+            --workspace-name "${{ inputs.workspace_name_01 }}" \
+            --git-ref "${{ inputs.git_ref }}" \
+            --image-tag "${{ inputs.image_tag }}" \
+            --tier "basic" \
+            --lb-type "shared"
+          # install sdk
+          if ! hash nvidia-smi 2>/dev/null; then
+             echo "nvidia-smi not found on host, installing cpu version of torch"
+             pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
+          fi
+          pip install -e ./sdk
+          ./mothershipctl workspace wait \
+          --mothership-url https://mothership.cloud.lepton.ai/api/v1 \
+          --token "${{ secrets.MOTHERSHIP_TOKEN }}" \
+          --workspace-name "${{ inputs.workspace_name_01 }}" \
+          --timeout 10 \
+          --expected-state "ready"
+      - name: Run tests
+        run: |
+          sleep 120 # wait for envoy to be ready
+          go test -p 8 -timeout 3600s -v ./e2e-tests/... \
+            --workspace-url https://${{ inputs.workspace_name_01 }}.${{ needs.find-cluster.outputs.cluster }}.dev.lepton.ai/api/v1 \
+            --auth-token ${{ inputs.api_token_01 }} \
+            --external-endpoint-main-domain ${{ needs.find-cluster.outputs.cluster }}.dev.lepton.ai
+      - name: Delete ci workspace
+        if: always()
+        run: |
+          ./mothershipctl workspace delete \
+            --auto-approve \
+            --mothership-url https://mothership.cloud.lepton.ai/api/v1 \
+            --token "${{ secrets.MOTHERSHIP_TOKEN }}" \
+            --workspace-name "${{ inputs.workspace_name_01 }}"
+          ./mothershipctl workspace wait \
+            --mothership-url https://mothership.cloud.lepton.ai/api/v1 \
+            --token "${{ secrets.MOTHERSHIP_TOKEN }}" \
+            --workspace-name "${{ inputs.workspace_name_01 }}" \
             --timeout 10 \
             --expected-state "deleted"
