testing(sdk): install cpu version of torch in ci if no nvidia-smi detected (#2388)
technically detecting nvidia-smi (only) is not 100% safe, but it should
be good enough for CI


cc @xiang90

diff --git a/.github/workflows/test-sdk-cp310.yaml b/.github/workflows/test-sdk-cp310.yaml
--- a/.github/workflows/test-sdk-cp310.yaml
+++ b/.github/workflows/test-sdk-cp310.yaml
@@ -29,6 +29,10 @@ jobs:
     - name: Lint
       run: |
         cd sdk
+        if ! hash nvidia-smi 2>/dev/null; then
+           echo "nvidia-smi not found on host, installing cpu version of torch"
+           pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
+        fi
         pip install .[lint]
         ruff .
         black --check .
diff --git a/.github/workflows/test-sdk-cp37.yaml b/.github/workflows/test-sdk-cp37.yaml
--- a/.github/workflows/test-sdk-cp37.yaml
+++ b/.github/workflows/test-sdk-cp37.yaml
@@ -28,6 +28,10 @@ jobs:
     - name: Test with pytest
       run: |
         cd sdk
+        if ! hash nvidia-smi 2>/dev/null; then
+           echo "nvidia-smi not found on host, installing cpu version of torch"
+           pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
+        fi
         pip install .
         pip install -r leptonai/examples/requirements.txt
         pip install .[test]
