chore(github-actions): format all github workflow yaml files (#2525)

diff --git a/.github/workflows/test-sdk-cp310.yaml b/.github/workflows/test-sdk-cp310.yaml
--- a/.github/workflows/test-sdk-cp310.yaml
+++ b/.github/workflows/test-sdk-cp310.yaml
@@ -6,42 +6,41 @@ on:
       - .github/workflows/test-sdk-cp310.yaml
       - sdk/**
       - vectordb/**
-    branches: [ "**" ]
+    branches: ["**"]
 
 permissions:
   contents: read
 
 jobs:
   test:
-
     runs-on: self-hosted
 
     steps:
-    - uses: actions/checkout@v3
-    - name: Set up Python 3.10
-      uses: actions/setup-python@v4
-      with:
-        python-version: "3.10"
-        cache: 'pip' # caching pip dependencies
-    - name: Install dependencies
-      run: |
-        pip install -U pip setuptools
-    - name: Lint
-      run: |
-        cd sdk
-        if ! hash nvidia-smi 2>/dev/null; then
-           echo "nvidia-smi not found on host, installing cpu version of torch"
-           pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
-        fi
-        pip install .[lint]
-        ruff .
-        black --check .
-        cd -
-    - name: Test with pytest
-      run: |
-        cd sdk
-        pip install .
-        pip install -r leptonai/examples/requirements.txt
-        pip install .[test]
-        cd -
-        pytest -x sdk
+      - uses: actions/checkout@v3
+      - name: Set up Python 3.10
+        uses: actions/setup-python@v4
+        with:
+          python-version: "3.10"
+          cache: "pip" # caching pip dependencies
+      - name: Install dependencies
+        run: |
+          pip install -U pip setuptools
+      - name: Lint
+        run: |
+          cd sdk
+          if ! hash nvidia-smi 2>/dev/null; then
+             echo "nvidia-smi not found on host, installing cpu version of torch"
+             pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
+          fi
+          pip install .[lint]
+          ruff .
+          black --check .
+          cd -
+      - name: Test with pytest
+        run: |
+          cd sdk
+          pip install .
+          pip install -r leptonai/examples/requirements.txt
+          pip install .[test]
+          cd -
+          pytest -x sdk
